apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-hello-world
  labels:
    app: dotnet-hello-world
    kubernetes.azure.com/generator: devhub
  namespace: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-hello-world
  template:
    metadata:
      labels:
        app: dotnet-hello-world
    spec:
      containers:
        - name: dotnet-hello-world
          image: acrworkflow1723904841628.azurecr.io/image-workflow-1723904841628:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
