apiVersion: apps/v1
kind: Deployment
metadata:
  name: Dotnet
  labels:
    app: Dotnet
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1723906223523
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Dotnet
  template:
    metadata:
      labels:
        app: Dotnet
    spec:
      containers:
        - name: Dotnet
          image: acrworkflow1723906223523.azurecr.io/image-workflow-1723906223523:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
