apiVersion: v1
kind: Service
metadata:
  name: dotnet-hello-world
  namespace: hello-world
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: dotnet-hello-world
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000