apiVersion: v1
kind: Service
metadata:
  name: Dotnet
  namespace: namespace-workflow-1723906223523
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: Dotnet
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000